apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-app-deploy
  annotations:
    kubernetes.io/change-cause: "deploying v3"
spec:
  minReadySeconds: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: order-app-service
  replicas: 4
  template:
    metadata:
      labels:
        app: order-app-service
    spec:
      containers:
      - name: order-app-service
        image: shauryadeepraolji/orderapp:1.3
        ports:
        - containerPort: 8081
