apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-app-deploy
  annotations:
    kubernetes.io/change-cause: "deploying v2"
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      app:  order-app-service
  replicas: 4
  template:
    metadata:
      labels:
        app:  order-app-service
    spec:
      containers:
      - name:  order-app-service
        image: shauryadeepraolji/orderapp:1.2
        imagePullPolicy: Always
        ports:
        - name: "spring-app-port"
          containerPort: 8080