FROM openjdk:21
MAINTAINER email="raoljishauryadeep@gmail.com"
EXPOSE 8092
ADD target/*.jar bookapp.jar
ENTRYPOINT ["java", "-jar", "bookapp.jar"]

LABEL authors="shauryadeepsinh.raolji"
LABEL maintainer-email="raoljishauryadeep@gmail.com"